# Generated by Django 6.0.4 on 2026-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_description',
            field=models.TextField(blank=True, help_text='Tell potential applicants about your company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_location',
            field=models.CharField(blank=True, help_text='e.g., Lilongwe, Malawi', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Your company name', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True, help_text='https://www.example.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, choices=[('TECH', 'Technology'), ('HEALTH', 'Healthcare'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance'), ('AGRICULTURE', 'Agriculture'), ('HOSPITALITY', 'Hospitality'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
