# Generated by Django 6.0.4 on 2026-04-10 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-code')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Detailed requirements')),
                ('responsibilities', models.TextField(blank=True)),
                ('required_skills', models.TextField(help_text='Comma-separated skills: Python, Django, Project Management')),
                ('required_qualifications', models.TextField(blank=True, help_text='Required degrees, certifications')),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level (0-2 years)'), ('JUNIOR', 'Junior (2-4 years)'), ('MID', 'Mid Level (4-7 years)'), ('SENIOR', 'Senior (7-10 years)'), ('LEAD', 'Lead/Manager (10+ years)')], default='ENTRY', max_length=20)),
                ('years_of_experience_required', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required')),
                ('location_type', models.CharField(choices=[('MW_CITY', 'Malawi City'), ('MW_DIST', 'Malawi District'), ('INTL', 'International'), ('REMOTE', 'Remote')], default='MW_CITY', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Malawi', max_length=100)),
                ('location_display', models.CharField(blank=True, help_text="Formatted location for display (e.g., 'Lilongwe, Malawi')", max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('RM', 'Remote'), ('HY', 'Hybrid'), ('FL', 'Freelance')], default='FT', max_length=2)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='MWK', max_length=3)),
                ('salary_is_displayed', models.BooleanField(default=False)),
                ('application_url', models.URLField(blank=True, help_text='External application link', null=True)),
                ('application_email', models.EmailField(blank=True, help_text='Email for direct applications', max_length=254, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('ADMIN_CSV', 'Admin CSV Upload'), ('ADMIN_API', 'Admin API Fetch'), ('EMP_VERIFIED', 'Verified Employer'), ('USER_GEN', 'General User')], default='USER_GEN', max_length=20)),
                ('trust_score', models.IntegerField(default=50, help_text='0-100 score based on source and verification', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified_company', models.BooleanField(default=False)),
                ('has_suspicious_content', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('external_id', models.CharField(blank=True, help_text='ID from external system/API', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Original source URL if scraped/imported')),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'db_table': 'job_vacancies',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('EXPIRED', 'Job has expired'), ('INCORRECT', 'Incorrect information'), ('SUSPICIOUS', 'Suspicious posting'), ('SPAM', 'Spam or fake job'), ('OTHER', 'Other reason')], default='SUSPICIOUS', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('report_count_at_time', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.jobvacancy')),
            ],
            options={
                'db_table': 'job_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['expiry_date', 'is_approved'], name='job_vacanci_expiry__fcba73_idx'),
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['location_type', 'city'], name='job_vacanci_locatio_5487af_idx'),
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['job_type', 'experience_level'], name='job_vacanci_job_typ_997535_idx'),
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['trust_score'], name='job_vacanci_trust_s_a1f646_idx'),
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['date_posted', 'is_approved'], name='job_vacanci_date_po_747c37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobreport',
            unique_together={('job', 'reported_by')},
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['user', 'viewed_at'], name='job_views_user_id_2dd5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='job_views_job_id_994b7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
