# Generated by Django 6.0.4 on 2026-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry Level (0-2 years)'), ('JUNIOR', 'Junior (2-4 years)'), ('MID', 'Mid Level (4-7 years)'), ('SENIOR', 'Senior (7-10 years)'), ('LEAD', 'Lead/Manager (10+ years)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('RM', 'Remote'), ('HY', 'Hybrid'), ('FL', 'Freelance')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='location_type',
            field=models.CharField(blank=True, choices=[('MW_CITY', 'Malawi City'), ('MW_DIST', 'Malawi District'), ('INTL', 'International'), ('REMOTE', 'Remote')], max_length=20, null=True),
        ),
    ]
