# Generated by Django 6.0.4 on 2026-04-10 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDemandStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=255)),
                ('location_type', models.CharField(choices=[('CITY', 'City'), ('DISTRICT', 'District'), ('COUNTRY', 'Country')], max_length=20)),
                ('total_jobs', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('jobs_by_category', models.JSONField(default=dict)),
                ('jobs_by_experience', models.JSONField(default=dict)),
                ('avg_salary_min', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('avg_salary_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('top_skills', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_demand_stats',
                'indexes': [models.Index(fields=['location_name'], name='location_de_locatio_3886f6_idx'), models.Index(fields=['active_jobs'], name='location_de_active__944663_idx')],
                'unique_together': {('location_name', 'location_type')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_demand_skills', models.JSONField(default=dict, help_text='Skill name -> frequency count')),
                ('user_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('top_missing_skills', models.JSONField(default=list, help_text="Top 5 skills user doesn't have but are in demand")),
                ('analysis_summary', models.TextField(blank=True)),
                ('jobs_analyzed', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Gap Analysis',
                'verbose_name_plural': 'Skill Gap Analyses',
                'db_table': 'skill_gap_analyses',
            },
        ),
        migrations.CreateModel(
            name='UserInteractionVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_job_ids', models.JSONField(default=list)),
                ('saved_job_ids', models.JSONField(default=list)),
                ('applied_job_ids', models.JSONField(default=list)),
                ('category_preferences', models.JSONField(default=dict)),
                ('preferred_skills', models.JSONField(default=dict)),
                ('interaction_weight', models.FloatField(default=0.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_vector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction Vector',
                'verbose_name_plural': 'User Interaction Vectors',
                'db_table': 'user_interaction_vectors',
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_vector', models.JSONField(default=dict, help_text='Normalized skills with weights')),
                ('skill_keywords', models.TextField(blank=True, help_text='Cleaned skill keywords for matching')),
                ('experience_weight', models.FloatField(default=1.0)),
                ('location_preference_vector', models.JSONField(default=dict)),
                ('job_type_preferences', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('needs_recalculation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Profile',
                'verbose_name_plural': 'User Skill Profiles',
                'db_table': 'user_skill_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skill_match_score', models.FloatField(default=0)),
                ('experience_match_score', models.FloatField(default=0)),
                ('location_match_score', models.FloatField(default=0)),
                ('job_type_match_score', models.FloatField(default=0)),
                ('freshness_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('match_reason', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='jobs.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_match_scores',
                'ordering': ['-match_score'],
                'indexes': [models.Index(fields=['user', 'match_score'], name='job_match_s_user_id_e23629_idx'), models.Index(fields=['job', 'match_score'], name='job_match_s_job_id_cd3d81_idx'), models.Index(fields=['calculated_at'], name='job_match_s_calcula_a00f74_idx')],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('HOMEPAGE', 'Homepage Feed'), ('SEARCH', 'Search Results'), ('EMAIL', 'Email Notification'), ('SIMILAR', 'Similar Jobs')], max_length=50)),
                ('match_score', models.FloatField()),
                ('position_in_list', models.IntegerField(default=0)),
                ('was_viewed', models.BooleanField(default=False)),
                ('was_saved', models.BooleanField(default=False)),
                ('was_ignored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobvacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_38c571_idx'), models.Index(fields=['job', 'created_at'], name='recommendat_job_id_1ff4e1_idx'), models.Index(fields=['recommendation_type', 'was_viewed'], name='recommendat_recomme_b2d385_idx')],
            },
        ),
    ]
