# Generated by Django 6.0.4 on 2026-04-10 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('CSV_URL', 'CSV File URL'), ('API_JSON', 'JSON API Endpoint'), ('API_XML', 'XML API Endpoint'), ('GOOGLE_SHEETS', 'Google Sheets')], max_length=20)),
                ('url', models.URLField(help_text='API endpoint or CSV file URL')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('auth_type', models.CharField(choices=[('NONE', 'None'), ('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth')], default='NONE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('HOURLY', 'Every Hour'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MANUAL', 'Manual Only')], default='DAILY', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], max_length=20, null=True)),
                ('default_trust_score', models.IntegerField(default=90)),
                ('auto_approve', models.BooleanField(default=True)),
                ('field_mapping', models.JSONField(default=dict, help_text='Map source fields to JobVacancy fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='ingestion/csv/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('created_records', models.IntegerField(default=0)),
                ('updated_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='ingestion.datasource')),
            ],
            options={
                'db_table': 'ingestion_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
